CREATE TABLE `clb_leaseco_transaction` (
   `id` int(11) NOT NULL AUTO_INCREMENT,
   `user_id` int(11) NOT NULL,
   `leaseco_org_name` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
   `connection_name` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
   `employer_id` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
   `driver_name` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
   `transaction_type` tinyint(2) DEFAULT NULL COMMENT '1 = public session, 2=home session,3=home installation,4=monthly driver fee',
   `installation_status` tinyint(2) DEFAULT NULL COMMENT 'Deprecated; 0 = Unset, 1 = Not Scheduled, 2 = Scheduled, 3 = Completed, 4 = Higher Cost, 5 = Uninstallable, 6 = Unresponsive, 7 = Other',
   `installation_date` datetime DEFAULT NULL,
   `installer_id` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
   `installer_name` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
   `install_location` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
   `installation_company` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
   `home_serial_num` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
   `reimbursement_id` int(11) unsigned DEFAULT NULL,
   `currency_iso_code` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
   `amount` decimal(20,3) DEFAULT NULL,
   `subtotal_amount` decimal(20,3) DEFAULT '0.000',
   `vat_rate` decimal(4,2) DEFAULT '0.00',
   `vat_amount` decimal(10,3) DEFAULT '0.000',
   `actual_amount` decimal(20,3) unsigned DEFAULT NULL,
   `approved_amount` decimal(20,3) unsigned DEFAULT NULL,
   `create_date` datetime DEFAULT CURRENT_TIMESTAMP,
   `update_date` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
   `job_status` tinyint(2) unsigned DEFAULT '1' COMMENT '0 = Unset, 1 = Open, 2 = In Progress, 3 = Completed, 4 = Not Installed (deprecated), 5 = Install Scheduled, 6 = Site Survey Pending, 7 = Survey OK-Not Scheduled, 8 = Closed-Not Installed-Higher Cost, 9 = Closed-Not Installed-Uninstallable, 10 = Closed-Not Installed-Unresponsive, 11 = Closed-Not Installed-Other, 12 = Charger activation in process, 13 = Charger activated, 14 = Charger activation failed, 15 = Job on-hold by driver',
   `job_document` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
   `external_id` int(11) DEFAULT NULL COMMENT 'For home installation jobs, stores the ID of the record in the installer portal',
   `connection_id` int(11) NOT NULL,
   `completion_date` datetime DEFAULT NULL COMMENT 'date when job is marked completed',
   `driver_group_id` int(11) NOT NULL,
   `activation_date` datetime DEFAULT NULL,
   PRIMARY KEY (`id`),
   KEY `user_id` (`user_id`),
   KEY `connection_id` (`connection_id`)
) ENGINE=InnoDB AUTO_INCREMENT=27475 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
