CREATE TABLE `clb_business_details` (
    `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
    `account_id` int(11) unsigned NOT NULL COMMENT 'Reference clb_account (id)',
    `subscriber_id` int(11) unsigned NOT NULL COMMENT 'Reference clb_subscriber (id)',
    `connection_id` int(11) DEFAULT NULL,
    `company_id` int(11) DEFAULT NULL,
    `business_type` enum('LEASECO') COLLATE utf8mb4_unicode_ci NOT NULL,
    `provide_home_station` tinyint(3) unsigned DEFAULT NULL COMMENT '0 = NO, 1 = YES',
    `installation_org_id` int(11) unsigned DEFAULT NULL,
    `reimburse_home_charging` tinyint(3) unsigned DEFAULT NULL COMMENT '0 = NO, 1 = Yes',
    `max_reimburse_price` decimal(10,2) DEFAULT NULL,
    `pay_for_public_charging` tinyint(3) DEFAULT NULL COMMENT '0 = NO, 1 = Yes',
    `home_station_warranty` tinyint(1) NOT NULL DEFAULT '0' COMMENT '0 = NO, 1 = Yes',
    `address1` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `address2` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `city` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `state` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `state_code` varchar(8) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `country` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `country_id` int(11) unsigned DEFAULT NULL,
    `country_code` varchar(4) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `zipcode` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `contact_number` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `contact_number_dialing_code` smallint(5) DEFAULT NULL,
    `connection_approval_date` datetime DEFAULT NULL,
    `connection_discontinue_date` datetime DEFAULT NULL,
    `status` enum('PENDING','ACTIVE','DELETED') COLLATE utf8mb4_unicode_ci DEFAULT 'PENDING',
    `create_date` datetime DEFAULT CURRENT_TIMESTAMP,
    `update_date` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    `driver_group_id` int(11) DEFAULT NULL,
    `home_charging_data_sharing` tinyint(1) NOT NULL DEFAULT '0' COMMENT '0 = NO (default), 1 = Yes . See SEP-10380 for details',
    `home_installation_by_partner` tinyint(1) NOT NULL DEFAULT '0' COMMENT '0 = NO (default), 1 = Yes. Note that this is not a connection benefit per se, but only a UI property. See MOB-834 for details',
    PRIMARY KEY (`id`),
    KEY `account_id` (`account_id`,`business_type`),
    KEY `subscriber_id` (`subscriber_id`)
) ENGINE=InnoDB AUTO_INCREMENT=172965 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
