CREATE TABLE `clb_connections` (
                                   `id` int(11) NOT NULL AUTO_INCREMENT,
                                   `company_id` int(11) NOT NULL,
                                   `driver_group_id` int(11) NOT NULL COMMENT 'driver group associated with this connectiton',
                                   `category_id` int(11) DEFAULT NULL,
                                   `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
                                   `state` enum('DISABLED','ENABLED') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'ENABLED',
                                   `type` enum('NORMAL','MFHS','LEASECO') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'NORMAL' COMMENT 'NORMAL: normal connection, MFHS: specify kind of MFHS Charging Connections, LEASECO: specify leaseco connection',
                                   `is_type_default` enum('NO','YES') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'NO' COMMENT 'Yes, for deault connection per type, if not set then first connection for that type would be marked YES',
                                   `code` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
                                   `field` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
                                   `logo` mediumblob,
                                   `logo_extension` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
                                   `logo_name` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
                                   `display_org_name` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
                                   `available_to` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
                                   `benefits` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
                                   `approval_mode` enum('AUTO','MANUAL') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'MANUAL',
                                   `custom_terms_status` enum('DISABLED','ENABLED') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'DISABLED',
                                   `custom_terms` mediumtext COLLATE utf8mb4_unicode_ci,
                                   `tc_acceptance_email` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
                                   `is_legacy` enum('NO','YES') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'NO' COMMENT 'YES are connections which we are migrated from old org level connections, otherwise NO',
                                   `company_property_id` int(11) DEFAULT NULL COMMENT 'THIS column kept here temporary. Will not be used anywhere in code and will be dropped before feature rollout.',
                                   `employer_id` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Its a customer Id field in connection form for leaseco connection',
                                   `provide_home_station` tinyint(1) DEFAULT NULL COMMENT '0 = NO, 1 = Yes',
                                   `installation_org_id` int(11) DEFAULT NULL,
                                   `reimburse_home_charging` tinyint(1) DEFAULT NULL COMMENT '0 = NO, 1 = Yes',
                                   `max_reimburse_price` decimal(10,2) DEFAULT NULL COMMENT 'Max amount per kwh the org will reimburse a driver for home charging, in the org currency',
                                   `pay_for_public_charging` tinyint(1) DEFAULT NULL COMMENT '0 = NO, 1 = Yes',
                                   `home_station_warranty` tinyint(1) NOT NULL DEFAULT '0' COMMENT '0 = NO, 1 = Yes',
                                   `web_only` tinyint(1) NOT NULL DEFAULT '0' COMMENT '0 = NO, 1 = Yes',
                                   `external_reporting_id` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'ID used by BizApps to refer to this connection',
                                   `support_email` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
                                   `tiny_url` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
                                   `create_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                   `template_id` int(11) DEFAULT NULL,
                                   `is_migrated` int(11) NOT NULL DEFAULT '0',
                                   `update_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                   PRIMARY KEY (`id`),
                                   KEY `fk_connections_company_id_idx` (`company_id`),
                                   KEY `fk_connections_driver_group_idx` (`driver_group_id`),
                                   KEY `fk_connections_category_id_idx` (`category_id`),
                                   KEY `FK_clb_connections_template_id` (`template_id`)
) ENGINE=InnoDB AUTO_INCREMENT=82365 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
