CREATE TABLE dms_home_charger_requests
(
    id                    INT(11)          UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    driver_id             INT(11)          NOT NULL,
    company_id            INT(11)          NOT NULL,
    connection_id         INT(11)          NOT NULL,
    driver_group_id       INT(11)          NOT NULL,
    leaseco_org_id        VARCHAR(25)      NOT NULL COMMENT 'Unique id generated for all the companies',
    leaseco_org_name      VARCHAR(100)     NOT NULL COMMENT 'Visible org name on connection',
    currency_iso_code     CHAR(3)          NULL COMMENT 'Driver currency',
    connection_name       VARCHAR(100)     DEFAULT NULL,
    driver_first_name     VARCHAR(255)     DEFAULT NULL,
    driver_last_name      VARCHAR(255)     DEFAULT NULL,
    request_status        VARCHAR(25)      NOT NULL DEFAULT 'REQUESTED',
    charger_deactivated   BOOL             NOT NULL DEFAULT false,
    email                 VARCHAR(255)     NOT NULL,
    phone_number          VARCHAR(20)      DEFAULT NULL,
    dialing_code          VARCHAR(10)      DEFAULT NULL,
    address1              VARCHAR(500)     DEFAULT NULL,
    address2              VARCHAR(500)     DEFAULT NULL,
    zip_code              VARCHAR(15)      DEFAULT NULL,
    city                  VARCHAR(255)     DEFAULT NULL,
    country_id            INT(11)          DEFAULT NULL,
    country_code          VARCHAR(2)       DEFAULT NULL,
    country_name          VARCHAR(255)     DEFAULT NULL,
    state_id              INT(11)          DEFAULT NULL,
    state_code            VARCHAR(10)      DEFAULT NULL,
    state_name            VARCHAR(255)     DEFAULT NULL,
    driver_verf_values    TEXT             COMMENT 'JSON array of driver verification values in format [{"key": "", "value": ""}]',
    created_at            TIMESTAMP        DEFAULT CURRENT_TIMESTAMP,
    updated_at            TIMESTAMP        DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
