CREATE TABLE `dms_installer_jobs`
(
    `id`                INT(11)                 UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `request_id`        INT(11)                 UNSIGNED NOT NULL,
    `employer_id`       VARCHAR(100)            DEFAULT NULL,
    `installer_id`      VARCHAR(64)             DEFAULT NULL,
    `installer_name`    VARCHAR(100)            DEFAULT NULL,
    `mac_address`       VARCHAR(100)            DEFAULT NULL,
    `currency_iso_code` VARCHAR(10)             DEFAULT NULL,
    `amount`            DECIMAL(20, 3)          DEFAULT NULL,
    `subtotal_amount`   DECIMAL(20, 3)          DEFAULT '0.000',
    `vat_rate`          DECIMAL(4, 2)           DEFAULT '0.00',
    `vat_amount`        DECIMAL(10, 3)          DEFAULT '0.000',
    `actual_amount`     DECIMAL(20, 3) unsigned DEFAULT NULL,
    `approved_amount`   DECIMAL(20, 3) unsigned DEFAULT NULL,
    `created_at`        DATETIME                DEFAULT CURRENT_TIMESTAMP,
    `updated_at`        DATETIME                DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `installation_date` DATETIME                DEFAULT NULL,
    `activation_date`   DATETIME                DEFAULT NULL,
    `completion_date`   DATETIME                DEFAULT NULL COMMENT 'date when job is marked completed',
    `job_status`        VARCHAR(25)             NOT NULL DEFAULT 'OPEN',
    `job_document`      VARCHAR(255)            DEFAULT NULL,
    `external_id`       INT(11)                 DEFAULT NULL COMMENT 'For home installation jobs, stores the ID of the record in the installer portal',
    `synced_to_nos`     BOOL                    DEFAULT FALSE COMMENT 'Indicates that the job was created on the legacy system aka NOS',
    FOREIGN KEY `FK_dms_home_charger_requests_request_id` (`request_id`) REFERENCES dms_home_charger_requests (`id`)
);
